In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_excel("C:\Dharan\Cheat Sheets\Datasets\Data_Train.xlsx")
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

### Step 1: Checking for missing values

In [3]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

### Step 2: Calculating the percentage of missing values

In [4]:
missing_percentage=(df.isnull().sum()/len(df)) * 100
missing_percentage

Airline            0.000000
Date_of_Journey    0.000000
Source             0.000000
Destination        0.000000
Route              0.009361
Dep_Time           0.000000
Arrival_Time       0.000000
Duration           0.000000
Total_Stops        0.009361
Additional_Info    0.000000
Price              0.000000
dtype: float64

### Step 3: Missing values in the form of DataFrame

In [5]:
missing_df=pd.DataFrame({
    'Missing Values':df.isnull().sum(),
    'Missing Percentage': (df.isnull().sum()/len(df))
})

missing_df

                 Missing Values  Missing Percentage
Airline                       0            0.000000
Date_of_Journey               0            0.000000
Source                        0            0.000000
Destination                   0            0.000000
Route                         1            0.000094
Dep_Time                      0            0.000000
Arrival_Time                  0            0.000000
Duration                      0            0.000000
Total_Stops                   1            0.000094
Additional_Info               0            0.000000
Price                         0            0.000000

### Step 3: Display only columns containing missing values

In [6]:
missing_df[missing_df["Missing Values"] > 0]

             Missing Values  Missing Percentage
Route                     1            0.000094
Total_Stops               1            0.000094

### Step 5: Remove missing values

In [7]:
df.dropna(inplace=True)

### Step 6: verify

In [8]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
dtype: int64

### 📝 Notebook conclusion

> The dataset contains only 2 missing values (Route and Total_Stops), accounting for less than 0.02% of the total records. Since the proportion of missing data is negligible, the affected rows were removed using dropna().

> This approach preserves data quality without significantly impacting the dataset size.

In [9]:
df.to_csv("Data_Train_Cleaned.csv", index=False)